import './search-room.scss';
import '../../less/media.scss';
import '../../main';
import '../../blocks/header/header';
import '../../blocks/dropdown/dropdown';
import '../../blocks/dropdown-date/dropdown-date';
import '../../blocks/range-slider/range-slider';
import '../../blocks/checkboxList/checkboxList';
import '../../blocks/rooms-catalog/rooms-catalog';
